### ISSUE TITLE
Do not work. Certificate signed by unknown authority

### ISSUE THREAD

**Issue by nlboom** [NHOrus/ponydownloader#10]
When I try to download images, this error happens:
`Errors at 2015/11/12 11:11:08. Error while getting search page 1.`
`Errors at 2015/11/12 11:11:08. Get https://derpiboo.ru/search.json?q=applelion&page=1: x509: certificate signed by unknown authority.`
[event.txt](https://github.com/NHOrus/ponydownloader/files/32701/event.txt)

**Comment by NHOrus** [comment]
What's your OS?
Based on this: https://github.com/golang/go/issues/9586 it's derpibooru problem.
I will add "Unsafe" flag that will allow to work with untrusted certificate chain.

**Comment by nlboom** [comment]
>What's your OS?

Windows XP SP3

**Comment by NHOrus** [comment]
Please try http://www.mediafire.com/download/1l1ltwp783rvj9x/ponydownloader-unsafe.exe
You need to run it with `--unsafe` flag for it to work

**Comment by nlboom** [comment]
>Please try http://www.mediafire.com/download/1l1ltwp783rvj9x/ponydownloader-unsafe.exe
>You need to run it with --unsafe flag for it to work

Not work, same error.
[event.txt](https://github.com/NHOrus/ponydownloader/files/33179/event.txt)

**Comment by NHOrus** [comment]
Sorry for delay in responses - was busy.

Then please try http://www.mediafire.com/download/k3psmj91gjpbuw8/ponydownloader-unsafer.exe
You need to run it with `--nohttps` flag. Hope it helps.

**Comment by NHOrus** [comment]
I got a problem while testing: It timeouts somewhy. On everything. Weird.

**Comment by nlboom** [comment]
>Then please try http://www.mediafire.com/download/k3psmj91gjpbuw8/ponydownloader-unsafer.exe

Not works for me again. 
>You need to run it with --nohttps flag. Hope it helps.

I tried use this command with `--unsafe` flag and without.
On my notebook with Windows 7 this program works fine, very strange.

[event.txt](https://github.com/NHOrus/ponydownloader/files/34957/event.txt)
[cmd.txt](https://github.com/NHOrus/ponydownloader/files/34958/cmd.txt)

**Comment by NHOrus** [comment]
I suspect why it doesn't run on XP - outdated root certificates.
I got no idea why it doesn't work with `--nohttps`. It should have turned entire security system off.

Can you try again with latest release - [0.5.3](https://github.com/NHOrus/ponydownloader/releases/tag/v0.5.3)? I reshuffled and tested things around, it didn't changed logic. If it helps - weird. If it doesn't - sorry. My every idea was rendered useless. Beyond my competence. Windows XP would be marked unsupported.

**Comment by nlboom** [comment]
>Can you try again with latest release - 0.5.3? I reshuffled and tested things around, it didn't changed logic. If it helps - weird.

Are still doesn't not working, same error.

> If it doesn't - sorry.

And you excuse me for your wasted time.

> Windows XP would be marked unsupported.

Very sad, I love my Windows XP.

**Comment by NHOrus** [comment]
In 12 hours I shall provide an version with a bit more tracing so we shall see exactly what's wrong with the certificates and what's exactly happens around the error.

But https://golang.org/src/crypto/x509/verify.go#L103 doesn't give me much hope - there is no additional info with error...

**Comment by NHOrus** [comment]
Done. http://www.mediafire.com/download/mt5uzwi9iw5y5vd/ponydownloader-tracing-1.exe
Please, try first just on single image, then on image but with `--nohttps` flag on. With `--unsafe` would also be interesting, if it woudn't help at all. On clear event.log. And give results. I prefer if you try with, say, image [1022254](https://derpibooru.org/1022254) , but it's up to you.

**Comment by NHOrus** [comment]
Ok, that thing woudn't work, either way. I found how to fix it, but it will a) take time and will leave app worse than it is
and b) better fixed if you update Root Certificate. As [written here](https://forum.startcom.org/viewtopic.php?t=954), and instruction should work for XP.

**Comment by nlboom** [comment]
>better fixed if you update Root Certificate. As written here, and instruction should work for XP.

Which one?
https://www.startssl.com/certs/

**Comment by NHOrus** [comment]
If i am reading correctly, [this one](https://www.startssl.com/certs/ca.cer).
Good luck.

**Comment by nlboom** [comment]
>If i am reading correctly, this one.

I am install it and reboot my PC, but this did not help.

**Comment by NHOrus** [comment]
Then shall try to fix it in three to four days, in different way.

**Comment by NHOrus** [comment]
Ok, it was... more interesting than I expected. On other hand, try [ponydownloader-new-unsafe](http://www.mediafire.com/download/y3mnrpm8049hpj5/ponydownloader-new-unsafe.exe) with `--unsafe-https` flag.

If it works, I will push changes and finally close the bug.

Good luck!

**Comment by nlboom** [comment]
>Ok, it was... more interesting than I expected. On other hand, try ponydownloader-new-unsafe with --unsafe-https flag.
If it works, I will push changes and finally close the bug.

Yes, it works fine. Thanks a lot!
