### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Pernat1y** [NHOrus/ponydownloader#25]
Hello.
When i'm running 
./ponydownloader-linux-amd64 --dir=dock --key=.... --tag=dock
i've got error: panic: runtime error: index out of range

Most of other tags works just fine.

Version 0.7.0
OS: Linux arch 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

More log:
[error.txt](https://github.com/NHOrus/ponydownloader/files/92982/error.txt)

**Comment by NHOrus** [comment]
Error is a lack of return 0 in correct place. Sadly, I currently completely lack access to derpibooru and unable to support the app.

Sorry.

**Comment by NHOrus** [comment]
Correction: fixed it in a582f6feff2936e2eb6873990ecd3aebf7e5aa63. Should work now. As I still unable to connect to derpibooru, please, try it yourself?

**Comment by Pernat1y** [comment]
Hello.
Seems fine. Thank you.
