### ISSUE TITLE
query.go:64: Incorrect request to server, error  404 Not Found

### ISSUE THREAD

**Issue by Pernat1y** [NHOrus/ponydownloader#29]
Downloader successfully gets the list (looking at url) but failed to download files itself:

$ ./ponydownloader-linux-amd64 --dir=test --key=<key> --tag=test
Derpibooru.org Downloader version 0.9.0
Happened at 2016/07/23 12:30:40 Program start
Happened at 2016/07/23 12:30:40 Processing tags test
Happened at 2016/07/23 12:30:40 Starting worker
Happened at 2016/07/23 12:30:40 Worker started; reading channel
Happened at 2016/07/23 12:30:40 Searching as https://derpibooru.org/search.json?q=test&key=<key>
Happened at 2016/07/23 12:30:40 Searching page 1
Happened at 2016/07/23 12:30:40 Searching page 2
Happened at 2016/07/23 12:30:40 Saving as 0.png
Happened at 2016/07/23 12:30:40 Saving as 0.gif
Happened at 2016/07/23 12:30:40 Saving as 0.gif
Happened at 2016/07/23 12:30:40 Saving as 0.gif
Happened at 2016/07/23 12:30:41 Searching page 3
Error at 2016/07/23 12:30:41 query.go:64: Incorrect request to server, error  404 Not Found
Error at 2016/07/23 12:30:41 query.go:65: Possible API changes
Happened at 2016/07/23 12:30:41 Saving as 0.jpg
Error at 2016/07/23 12:30:41 query.go:64: Incorrect request to server, error  404 Not Found
Error at 2016/07/23 12:30:41 query.go:65: Possible API changes
Happened at 2016/07/23 12:30:41 Saving as 0.png
Error at 2016/07/23 12:30:41 query.go:64: Incorrect request to server, error  404 Not Found
...

**Comment by NHOrus** [comment]
Sorry, missed your issue.
But it fixed in 406e9a8dccb948db1808b12e8c3a96f0ff16c78c and v0.9.1 works.
