### ISSUE TITLE
Derpibooru to trixiebooru

### ISSUE THREAD

**Issue by AnotherPony** [NHOrus/ponydownloader#33]
Hi. In russia [derpibooru.org](https://derpibooru.org) was banned (reason - roscomnadzor. You can see it on [derpiboo.ru](https://derpiboo.ru)).
And [trixiebooru.org](https://trixiebooru.org) still works.
So, i can change source files from derpi to trixie ('cause that's easy), but i don't know how to run it. Can you help me run it or can you make trixiebooru version of the program?

**Comment by NHOrus** [comment]
I got no idea that trixiebooru.org is an alias. Instructions to run are in readme.

Please wait for new release, it will be soon.

**Comment by NHOrus** [comment]
Done.
ad9a80f closes this issue
Thank you for pointing me to the correct target.

**Comment by AnotherPony** [comment]
Thanks.

**Comment by NHOrus** [comment]
And damn. Borked again.
